;1、规则组
ruleset=Drop,clash-classic:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanAD.yaml,28800
ruleset=Bing,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing_No_Resolve.yaml,28800
ruleset=Chatgpt,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml,28800
ruleset=Copilot,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot_No_Resolve.yaml,28800
ruleset=Gemini,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini_No_Resolve.yaml,28800
ruleset=🇺🇸 美国-飞鸟,clash-classic:https://raw.githubusercontent.com/KudaYoung/my_clash_rule/refs/heads/main/rule/US_classical.yaml,86400
ruleset=Proxy,clash-classic:https://raw.githubusercontent.com/KudaYoung/my_clash_rule/refs/heads/main/rule/proxy_classical.yaml,86400
ruleset=Proxy,clash-domain:https://raw.githubusercontent.com/KudaYoung/my_clash_rule/refs/heads/main/rule/proxy_domain.yaml,86400
ruleset=Google,[]GEOSITE,google
ruleset=Proxy,[]GEOSITE,gfw
ruleset=Direct,clash-classic:https://raw.githubusercontent.com/KudaYoung/my_clash_rule/refs/heads/main/rule/pass_classical.yaml,86400
ruleset=Direct,clash-domain:https://raw.githubusercontent.com/KudaYoung/my_clash_rule/refs/heads/main/rule/pass_domain.yaml,86400
ruleset=Drop,clash-classic:https://raw.githubusercontent.com/KudaYoung/my_clash_rule/refs/heads/main/rule/drop.yaml,86400
ruleset=Direct,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nvidia/Nvidia_No_Resolve.yaml,28800
ruleset=Apple,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple_Classical_No_Resolve.yaml,28800
ruleset=Microsoft,[]GEOSITE,microsoft
ruleset=Direct,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN_No_Resolve.yaml,28800
ruleset=Proxy,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Steam/Steam_No_Resolve.yaml,28800
ruleset=Direct,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Game/Game_No_Resolve.yaml,28800
ruleset=Telegram,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml,28800
ruleset=Direct,[]GEOSITE,cn
ruleset=Direct,[]GEOIP,cn,no-resolve
ruleset=非标端口,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Port_Direct.yaml,86400
ruleset=End,[]FINAL

;2、策略组（域名组-节点组）
custom_proxy_group=Proxy`select`[]自动选择`[]手动选择`[]飞鸟`[]一元`[]🇭🇰 香港-飞鸟`[]🇼🇸 台湾-飞鸟`[]🇯🇵 日本-飞鸟`[]🇸🇬 新加坡-飞鸟`[]🇺🇸 美国-飞鸟`[]🇲🇾 马来-飞鸟`[]🇬🇧 英国-飞鸟`[]其他-飞鸟`[]🇭🇰 香港-一元`[]🇯🇵 日本-一元`[]🇸🇬 新加坡-一元`[]🇺🇸 美国-一元`[]🇳🇱 荷兰-一元
custom_proxy_group=End`select`[]Proxy`[]自动选择`[]DIRECT`[]手动选择
custom_proxy_group=手动选择`select`.*
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=非标端口`select`[]DIRECT`[]Proxy`[]自动选择`[]手动选择
custom_proxy_group=飞鸟`url-test`(Hong Kong|Taiwan|Japan|Singapore|USA|Malaysia|UK|Argentina|Turkey)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=一元`url-test`(香港|日本|新加坡|美国|荷兰)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=Chatgpt`select`[]Proxy`[]自动选择`[]🇭🇰 香港-飞鸟`[]🇼🇸 台湾-飞鸟`[]🇯🇵 日本-飞鸟`[]🇸🇬 新加坡-飞鸟`[]🇺🇸 美国-飞鸟`[]🇲🇾 马来-飞鸟`[]🇬🇧 英国-飞鸟`[]其他-飞鸟`[]🇭🇰 香港-一元`[]🇯🇵 日本-一元`[]🇸🇬 新加坡-一元`[]🇺🇸 美国-一元`[]🇳🇱 荷兰-一元
custom_proxy_group=Gemini`select`[]Proxy`[]自动选择`[]🇭🇰 香港-飞鸟`[]🇼🇸 台湾-飞鸟`[]🇯🇵 日本-飞鸟`[]🇸🇬 新加坡-飞鸟`[]🇺🇸 美国-飞鸟`[]🇲🇾 马来-飞鸟`[]🇬🇧 英国-飞鸟`[]其他-飞鸟`[]🇭🇰 香港-一元`[]🇯🇵 日本-一元`[]🇸🇬 新加坡-一元`[]🇺🇸 美国-一元`[]🇳🇱 荷兰-一元
custom_proxy_group=Copilot`select`[]Proxy`[]自动选择`[]🇭🇰 香港-飞鸟`[]🇼🇸 台湾-飞鸟`[]🇯🇵 日本-飞鸟`[]🇸🇬 新加坡-飞鸟`[]🇺🇸 美国-飞鸟`[]🇲🇾 马来-飞鸟`[]🇬🇧 英国-飞鸟`[]其他-飞鸟`[]🇭🇰 香港-一元`[]🇯🇵 日本-一元`[]🇸🇬 新加坡-一元`[]🇺🇸 美国-一元`[]🇳🇱 荷兰-一元
custom_proxy_group=Google`select`[]Proxy`[]自动选择`[]🇭🇰 香港-飞鸟`[]🇼🇸 台湾-飞鸟`[]🇯🇵 日本-飞鸟`[]🇸🇬 新加坡-飞鸟`[]🇺🇸 美国-飞鸟`[]🇲🇾 马来-飞鸟`[]🇬🇧 英国-飞鸟`[]其他-飞鸟`[]🇭🇰 香港-一元`[]🇯🇵 日本-一元`[]🇸🇬 新加坡-一元`[]🇺🇸 美国-一元`[]🇳🇱 荷兰-一元
custom_proxy_group=Telegram`select`[]Proxy`[]自动选择`[]🇭🇰 香港-飞鸟`[]🇼🇸 台湾-飞鸟`[]🇯🇵 日本-飞鸟`[]🇸🇬 新加坡-飞鸟`[]🇺🇸 美国-飞鸟`[]🇲🇾 马来-飞鸟`[]🇬🇧 英国-飞鸟`[]其他-飞鸟`[]🇭🇰 香港-一元`[]🇯🇵 日本-一元`[]🇸🇬 新加坡-一元`[]🇺🇸 美国-一元`[]🇳🇱 荷兰-一元
custom_proxy_group=Apple`select`[]DIRECT`[]自动选择
custom_proxy_group=Microsoft`select`[]DIRECT`[]自动选择
custom_proxy_group=Bing`select`[]DIRECT`[]自动选择
custom_proxy_group=Direct`select`[]DIRECT
custom_proxy_group=Drop`select`[]REJECT`[]DIRECT
;3、飞鸟
custom_proxy_group=🇭🇰 香港-飞鸟`url-test`(Hong Kong|HongKong)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=🇼🇸 台湾-飞鸟`url-test`(Tai Wan|TaiWan|Taiwan)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=🇯🇵 日本-飞鸟`url-test`(Japan)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=🇸🇬 新加坡-飞鸟`url-test`(Singapore)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=🇺🇸 美国-飞鸟`url-test`(USA)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=🇲🇾 马来-飞鸟`url-test`(Malaysia)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=🇬🇧 英国-飞鸟`url-test`(UK)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=其他-飞鸟`url-test`(Argentina|Turkey)`http://www.gstatic.com/generate_204`180,5,30
;4、一元
custom_proxy_group=🇭🇰 香港-一元`url-test`(香港)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=🇯🇵 日本-一元`url-test`(日本)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=🇸🇬 新加坡-一元`url-test`(新加坡)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=🇺🇸 美国-一元`url-test`(美国)`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=🇳🇱 荷兰-一元`url-test`(荷兰)`http://www.gstatic.com/generate_204`180,5,30

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
