;1、规则组
ruleset=Proxy,[]GEOSITE,github
ruleset=Direct,[]GEOSITE,apple
ruleset=Direct,[]GEOSITE,microsoft
ruleset=Direct,[]GEOSITE,nvidia
ruleset=Direct,[]GEOSITE,cn
ruleset=Direct,[]GEOIP,cn,no-resolve
ruleset=Proxy,[]FINAL

;2、策略组
custom_proxy_group=Proxy`select`[]自动选择`[]手动选择`[]DIRECT
custom_proxy_group=手动选择`select`.*
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=Direct`select`[]DIRECT

;3、生成配置
enable_rule_generator=true
overwrite_original_rules=true
