;1、规则组
ruleset=Proxy,[]GEOSITE,gfw
ruleset=Proxy,[]GEOSITE,github
ruleset=Proxy,[]GEOSITE,telegram
ruleset=Proxy,[]GEOSITE,openai
ruleset=Proxy,[]GEOSITE,gemini
ruleset=Proxy,[]GEOSITE,google
ruleset=Proxy,[]GEOSITE,twitter
ruleset=Proxy,[]GEOSITE,spotify
ruleset=Proxy,[]GEOSITE,disney
ruleset=Direct,[]FINAL

;2、策略组
custom_proxy_group=Proxy`select`[]自动选择`[]手动选择`[]DIRECT
custom_proxy_group=手动选择`select`.*
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`180,5,30
custom_proxy_group=Direct`select`[]DIRECT

;3、生成配置
enable_rule_generator=true
overwrite_original_rules=true
